# Generated by Django 3.1.7 on 2021-03-04 17:49

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp',
            name='cover_image',
            field=stdimage.models.StdImageField(default='./static/img/logo1.png', upload_to=core.models.get_file_path, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='lp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
